#!/usr/bin/env python3
"""gate-report.py — summarise human gate-wait from the gate log.

Companion reader to `.claude/hooks/gate-log.py`, which captures every
Stop→UserPromptSubmit interval. This turns those rows into the two things
Phase 4A needs: **how long the humans took**, and **which gates they took it on**.

Why a separate script rather than reading the TSV in context: the same reason as
`aggregate-telemetry.py`. A long interactive cycle produces a row per turn, and
the orchestrator needs a summary, not a transcript.

Gate-wait is the number W1 got wrong and §18.5 singled out as unmeasured. It is
also the input to any future decision about how many cycles can run at once, since
a human answering gates is the shared resource that concurrency contends for.

    gate-report.py                    # this cycle
    gate-report.py --log <path>       # a run-level log from a parallel fan-out
    gate-report.py --all              # every interval, not just named gates
    gate-report.py --json

Never invents a plausible-looking zero: no log means "not captured", which is a
different claim from "nobody waited".

Exit codes: 0 always (a missing log is information, not an error).
"""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys
from datetime import datetime, timezone

COLUMNS = ("raised_at", "answered_at", "wait_s", "cycle", "issue",
           "gate", "phase", "excerpt", "answer")

# Intervals not matched to a named gate are ordinary conversational turns. They
# are kept in the log (see the hook's two-tier note) but excluded from the gate
# summary unless --all, or they would swamp the distribution they belong to.
UNNAMED = ("-", "question")

# A `wakeup` interval ended when a background agent finished, not when a person
# answered. It is never human wait and is never included in a gate figure, even
# under --all. Fan-out 2 logged 33 intervals of which 30 were these; reporting the
# combined total gave 40m36s against an actual human wait of 59 seconds, and only
# an orchestrator inspecting the raw log caught it (evidence-run2 F3).
WAKEUP = "wakeup"

# Recognise a wakeup from the recorded answer as well as from the label. Two
# reasons: logs written before the hook learned to classify them are still worth
# reading, and a prefix the hook does not know about should not silently become
# "human wait" here.
# Must stay identical to WAKEUP_PREFIXES in .claude/hooks/gate-log.py — pinned by
# tests/test_gate_log.py. They drifted once already: the hook had a fourth entry
# this list lacked, so a row the hook would have called a wakeup was counted here
# as human wait — a scaled-down instance of the bug this whole mechanism fixes.
WAKEUP_ANSWER = ("<task-notification>", "<system-reminder>", "[system notification")

# Neither human wait nor an agent wakeup — see LOCAL_COMMAND_PREFIXES in the hook.
# Counted apart from both, because putting an unclassified interval into either
# total makes that total quietly wrong, and quietly wrong is the failure this
# whole mechanism exists to correct.
LOCAL_CMD = "local-cmd"
LOCAL_CMD_ANSWER = ("caveat: the messages below were generated by the user while running",)

# Idle before a cycle existed — neither gate wait nor an agent wakeup. Counted
# apart for the same reason local-cmd is: putting it in either total makes that
# total quietly wrong. Must stay identical to the label the hook writes and to
# its RESUME_PREFIXES / MERGE_ANSWERS — pinned by tests/test_gate_log.py.
PRE_CYCLE = "pre-cycle"
RESUME_PREFIXES = ("--exe", "--continue", "--resume")
MERGE_ANSWERS = frozenset((
    "merged", "merged it", "pr merged", "its merged", "it's merged",
    "merged and closed",
))

# Human wait, but not *gate* wait. A permission dialog blocks the cycle just as a
# gate does, yet it is not a decision the pipeline chose to ask for — it is the
# harness interrupting. Merging the two would make "gate wait" mean two things and
# would hide the thing worth seeing: a cycle can be blocked for hours on an ask
# nobody noticed, with every gate answered promptly.
#
# Must stay identical to the label written by `.claude/hooks/gate-log.py`'s
# on_post_tool — pinned by tests/test_gate_log.py, for the same reason the wakeup
# lists are pinned.
PERMISSION = "permission"

# A refused tool call. Not human wait, not agent wait, not a gate — nobody was
# asked anything. It is here because it was invisible everywhere else: in
# fan-out 7 three tool calls were refused across two clones and the run reported
# "0 permission wait", which was true about dialogs and silent about refusals.
# `PostToolUse` never fires on a refusal, so the hook reads it from the
# transcript at Stop/SubagentStop and writes it with `wait_s` 0.
#
# Counted and reported apart, never folded into any wait figure: a refusal costs
# an agent a retry or a capability, not a person their time, and adding zero-wait
# rows to the permission set would drag its mean toward zero.
DENIAL = "denial"
# Must stay identical to NOT_PERMISSION_TOOLS in .claude/hooks/gate-log.py —
# pinned by tests/test_gate_log.py, like the wakeup and merge lists.
NOT_PERMISSION_TOOLS = frozenset(("AskUserQuestion",))
PERMISSION_ANSWER = ("[permission granted",)

# Where the hook parks an ask that was never granted. Same name on both sides or
# the stall this exists to surface is silently unreadable — pinned by the tests.
PERM_DIR = "permission-open"


def is_wakeup(row: dict) -> bool:
    if row.get("gate") == WAKEUP:
        return True
    ans = (row.get("answer") or "").lstrip().lower()
    return any(ans.startswith(p) for p in WAKEUP_ANSWER)


def is_denial(row: dict) -> bool:
    return row.get("gate") == DENIAL


def is_permission(row: dict) -> bool:
    if row.get("gate") == PERMISSION:
        return True
    ans = (row.get("answer") or "").lstrip().lower()
    return any(ans.startswith(p) for p in PERMISSION_ANSWER)


def is_local_cmd(row: dict) -> bool:
    if row.get("gate") == LOCAL_CMD:
        return True
    ans = (row.get("answer") or "").lstrip().lower()
    return any(ans.startswith(p) for p in LOCAL_CMD_ANSWER)


def is_pre_cycle(row: dict) -> bool:
    """An interval that ended when a person *started* a cycle.

    Nobody was being asked anything: the session was idle, waiting to be given
    work. Recognised from the answer as well as the label so logs written before
    the hook learned this still read correctly — and they badly need it. The two
    largest non-permission intervals in fan-out 4 are both of these (32m33s and
    11h12m), and counted as human wait they are a person asleep, not a pipeline
    waiting on a decision.
    """
    if row.get("gate") == PRE_CYCLE:
        return True
    ans = " ".join((row.get("answer") or "").split()).lower()
    if not ans.startswith("/cycle"):
        return False
    rest = ans[len("/cycle"):].strip()
    return bool(rest) and not rest.startswith(RESUME_PREFIXES)


def retro_gate(row: dict) -> str:
    """Name an unnamed gate from the answer — see the hook's tier 3.

    Only ever applied to a row the hook left unnamed, so it cannot overwrite a
    label taken from the question itself.
    """
    ans = " ".join((row.get("answer") or "").split()).lower().rstrip(".!")
    if ans in MERGE_ANSWERS:
        return "pr-merge"
    if ans.startswith("/cycle") and ans[len("/cycle"):].strip().startswith(RESUME_PREFIXES):
        return "resume"
    return ""


def repo_root() -> pathlib.Path:
    try:
        out = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                             capture_output=True, text=True, timeout=10)
        if out.returncode == 0 and out.stdout.strip():
            top = pathlib.Path(out.stdout.strip()).resolve()
            if (top / "agent_states" / ".fanout-clone").exists():
                return top
            common = subprocess.run(["git", "rev-parse", "--git-common-dir"],
                                    capture_output=True, text=True, timeout=10)
            if common.returncode == 0 and common.stdout.strip():
                return pathlib.Path(common.stdout.strip()).resolve().parent
            return top
    except (OSError, subprocess.SubprocessError):
        pass
    return pathlib.Path.cwd()


def read_rows(path: pathlib.Path) -> list[dict]:
    rows = []
    try:
        lines = path.read_text(errors="replace").splitlines()
    except OSError:
        return rows
    for line in lines:
        parts = line.split("\t")
        if not parts or parts[0] in ("raised_at", ""):
            continue
        row = dict(zip(COLUMNS, parts + ["-"] * (len(COLUMNS) - len(parts))))
        try:
            row["wait"] = int(row["wait_s"])
        except (ValueError, TypeError):
            continue
        rows.append(row)
    return rows


def hms(seconds: float) -> str:
    s = int(round(seconds))
    if s < 60:
        return f"{s}s"
    if s < 3600:
        return f"{s // 60}m{s % 60:02d}s"
    return f"{s // 3600}h{(s % 3600) // 60:02d}m"


def quantile(values: list[int], q: float) -> float:
    if not values:
        return 0.0
    s = sorted(values)
    if len(s) == 1:
        return float(s[0])
    pos = q * (len(s) - 1)
    lo = int(pos)
    hi = min(lo + 1, len(s) - 1)
    return s[lo] + (s[hi] - s[lo]) * (pos - lo)


def open_gate(root: pathlib.Path) -> dict | None:
    """A gate raised and never answered — a parked or abandoned cycle.

    This is the case §18.5 flagged as producing no report at all, so it is
    reported first and separately from the answered distribution.
    """
    try:
        rec = json.loads((root / "agent_states" / "gate-open.json").read_text())
    except (OSError, ValueError):
        return None
    try:
        raised = datetime.strptime(rec["raised_at"], "%Y-%m-%dT%H:%M:%SZ").replace(
            tzinfo=timezone.utc)
        rec["waiting_s"] = int((datetime.now(timezone.utc) - raised).total_seconds())
    except Exception:
        rec["waiting_s"] = None
    return rec


def open_permissions(root: pathlib.Path) -> list[dict]:
    """Permission asks raised and never granted — the c1 signature.

    An ask that was denied, or that nobody ever clicked, produces no PostToolUse
    and so never closes. That lingering record is the only evidence a cycle stalled
    on a dialog, so it is read here and reported before anything else.
    """
    out = []
    d = root / "agent_states" / PERM_DIR
    try:
        names = sorted(d.iterdir())
    except OSError:
        return out
    now = datetime.now(timezone.utc)
    for f in names:
        try:
            rec = json.loads(f.read_text())
        except (OSError, ValueError):
            continue
        try:
            raised = datetime.strptime(rec["raised_at"], "%Y-%m-%dT%H:%M:%SZ").replace(
                tzinfo=timezone.utc)
            rec["waiting_s"] = int((now - raised).total_seconds())
        except Exception:
            rec["waiting_s"] = None
        out.append(rec)
    return sorted(out, key=lambda r: r.get("waiting_s") or 0, reverse=True)


def print_denials(denials: list[dict]) -> None:
    """Refusals, counted apart from every wait figure.

    Nobody waited on these — the point is that they happened at all and that
    probe 12 could not see them. Report the reason and the actor, because the
    fix differs: a classifier refusal on a sanctioned script is a grant to widen
    or a script to scope, and a user rejection is not a harness problem at all.
    """
    if not denials:
        return
    by_reason: dict[str, int] = {}
    by_actor: dict[str, int] = {}
    for r in denials:
        ans = (r.get("answer") or "").strip()
        reason = ans[len("[denied:"):].rstrip("]").strip() if ans.startswith("[denied:") else "unspecified"
        by_reason[reason] = by_reason.get(reason, 0) + 1
        actor = (r.get("phase") or "-").strip() or "-"
        by_actor[actor] = by_actor.get(actor, 0) + 1
    print()
    print(f"  {len(denials)} tool call(s) refused — no dialog, no wait, and invisible to the")
    print("  permission figures above. `PostToolUse` does not fire on a refusal.")
    for reason, n in sorted(by_reason.items(), key=lambda kv: -kv[1]):
        print(f"    {n:>3}  {reason}")
    print("    by actor: " + ", ".join(f"{a} {n}" for a, n in
                                       sorted(by_actor.items(), key=lambda kv: -kv[1])))
    print("  Reproduce these in the run report — a refusal an agent worked around is")
    print("  still a capability the pipeline does not have.")


def print_open_permissions(pending: list[dict]) -> None:
    if not pending:
        return
    print()
    for rec in pending:
        waiting = rec.get("waiting_s")
        print(f"  ! OPEN permission ask raised {rec.get('raised_at', '?')}"
              + (f", waiting {hms(waiting)}" if waiting is not None else "")
              + " — never granted, and not counted above.")
        if rec.get("excerpt"):
            print(f"    {rec['excerpt'][:100]}")
    print("    A cycle blocked here looks idle in every other record. Answer it, or "
          "widen the permission.")


def print_open(pending: dict | None) -> None:
    """An unanswered gate is a live cost, not a data point — say so separately."""
    if not pending:
        return
    waiting = pending.get("waiting_s")
    print()
    print(f"  ! OPEN gate '{pending.get('gate', '-')}' raised "
          f"{pending.get('raised_at', '?')}"
          + (f", waiting {hms(waiting)}" if waiting is not None else "")
          + " — unanswered, and not counted above.")
    if pending.get("excerpt"):
        print(f"    {pending['excerpt'][:100]}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--log", help="path to a gate log (default: this cycle's)")
    ap.add_argument("--all", action="store_true",
                    help="include human intervals that matched no named gate. Wakeups stay excluded — they are never human wait")
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    args = ap.parse_args()

    root = repo_root()
    path = pathlib.Path(args.log) if args.log else root / "agent_states" / "gate-log.tsv"
    pending = open_gate(root)
    pending_perms = open_permissions(root)

    if not path.exists():
        # A cycle parked at its FIRST gate has an open record and no log at all.
        # That is the exact case §18.5 flags as producing no report, so it must
        # not be swallowed by the missing-log path.
        msg = (f"Gate wait not captured — no log at {path}. "
               "Wire the Stop/UserPromptSubmit hooks per README, or the cycle ran "
               "before they existed. This is not the same as 'no gates were raised'.")
        if args.json:
            print(json.dumps({"captured": False, "reason": msg, "open": pending,
                              "open_permissions": pending_perms}, indent=2))
        else:
            print(msg)
            print_open(pending)
            print_open_permissions(pending_perms)
        return 0

    rows = read_rows(path)
    denials = [r for r in rows if is_denial(r)]
    rows = [r for r in rows if not is_denial(r)]
    perms = [r for r in rows if is_permission(r)]
    rest = [r for r in rows if not is_permission(r)]
    wakeups = [r for r in rest if is_wakeup(r)]
    local = [r for r in rest if not is_wakeup(r) and is_local_cmd(r)]
    pre = [r for r in rest if not is_wakeup(r) and not is_local_cmd(r) and is_pre_cycle(r)]
    human = [r for r in rest
             if not is_wakeup(r) and not is_local_cmd(r) and not is_pre_cycle(r)]
    # Tier 3, applied on read so that logs written before the hook learned it are
    # still readable. Only touches rows the question left unnamed.
    for r in human:
        if r["gate"] in UNNAMED:
            r["gate"] = retro_gate(r) or r["gate"]
    gates = human if args.all else [r for r in human if r["gate"] not in UNNAMED]
    waits = [r["wait"] for r in gates]
    unclassified = [r for r in human if r["gate"] in UNNAMED]

    by_gate: dict[str, list[int]] = {}
    for r in gates:
        by_gate.setdefault(r["gate"], []).append(r["wait"])

    if args.json:
        print(json.dumps({
            "captured": True,
            "denials": [{"reason": (r.get("answer") or ""), "actor": r.get("phase"),
                         "excerpt": r.get("excerpt"), "at": r.get("raised_at")}
                        for r in denials],
            "denial_count": len(denials),
            "log": str(path),
            "intervals_total": len(rows),
            "gates": len(gates),
            "wait_total_s": sum(waits),
            "median_s": quantile(waits, 0.5),
            "p90_s": quantile(waits, 0.9),
            "max_s": max(waits) if waits else 0,
            "by_gate": {k: {"n": len(v), "total_s": sum(v),
                            "median_s": quantile(v, 0.5), "max_s": max(v)}
                        for k, v in sorted(by_gate.items())},
            "wakeups": {"n": len(wakeups), "total_s": sum(r["wait"] for r in wakeups),
                        "note": "agent-completion wakeups, not human wait — excluded above"},
            "pre_cycle": {"n": len(pre), "total_s": sum(r["wait"] for r in pre),
                          "note": "session idle before a cycle started — counted in "
                                  "neither total"},
            "local_commands": {"n": len(local), "total_s": sum(r["wait"] for r in local),
                               "note": "neither human wait nor agent wakeup — unresolved, "
                                       "counted in neither total"},
            "unclassified": len(unclassified),
            "permissions": {"n": len(perms),
                            "total_s": sum(r["wait"] for r in perms),
                            "max_s": max((r["wait"] for r in perms), default=0),
                            "note": "human wait on a harness permission dialog — real "
                                    "idle time, but not gate wait; counted apart"},
            "open": pending,
            "open_permissions": pending_perms,
        }, indent=2))
        return 0

    print(f"Gate wait — {path}")
    if wakeups:
        print(f"  {len(wakeups)} of {len(rows)} interval(s) ended on an agent-completion wakeup, "
              f"not a person ({hms(sum(r['wait'] for r in wakeups))} total).")
        print("  Those are NOT human wait and are excluded below.")
    if perms:
        total = sum(r["wait"] for r in perms)
        print(f"  {len(perms)} permission prompt(s) blocked the cycle for {hms(total)} "
              f"(max {hms(max(r['wait'] for r in perms))}) — human wait, but not gate "
              f"wait, so counted apart from both.")
        for r in sorted(perms, key=lambda r: -r["wait"])[:5]:
            print(f"    {hms(r['wait']):>8}  {r['excerpt'][:80]}")
    if pre:
        print(f"  {len(pre)} interval(s) ended when a person started a cycle "
              f"({hms(sum(r['wait'] for r in pre))} total) — the session was idle, not "
              f"waiting on a gate, so counted in neither.")
    if local:
        print(f"  {len(local)} interval(s) ended on a local-command wrapper "
              f"({hms(sum(r['wait'] for r in local))} total) — not established as human or "
              f"machine, so counted in neither.")
    if unclassified:
        ex = next((r["excerpt"] for r in unclassified if r["excerpt"].startswith("[unclassified:")), "")
        print(f"  {len(unclassified)} human interval(s) could not be matched to a named gate"
              + (f" {ex}" if ex else "") + " — counted, unlabelled.")
    if not gates:
        print(f"  {len(rows)} interval(s) logged, none classified as a gate."
              + ("" if args.all else "  Use --all to see them."))
    else:
        print(f"  {len(gates)} gate(s) across {len(human)} human interval(s)")
        print(f"  total {hms(sum(waits))}   median {hms(quantile(waits, 0.5))}"
              f"   p90 {hms(quantile(waits, 0.9))}   max {hms(max(waits))}")
        print()
        print(f"  {'gate':<10} {'n':>3}  {'total':>8} {'median':>8} {'max':>8}")
        for name, vals in sorted(by_gate.items(), key=lambda kv: -sum(kv[1])):
            print(f"  {name:<10} {len(vals):>3}  {hms(sum(vals)):>8} "
                  f"{hms(quantile(vals, 0.5)):>8} {hms(max(vals)):>8}")

    print_denials(denials)
    print_open(pending)
    print_open_permissions(pending_perms)
    return 0


if __name__ == "__main__":
    sys.exit(main())
